### DISCUSSION TITLE
Voice-driven Cart ↔ Shopping-list Sync

### DISCUSSION THREAD

**Discussion by eMeF1** [dvejsada/HA-RohlikCZ#37] [Use Cases]
## 🤝 Contribute
This automation is still evolving! If you have ideas to improve usability, add new features, or fix edge cases — please let me know. It can be later turned into a **Home Assistant Blueprint** once the logic is refined and edge cases are handled. 

# 🛒 Home Assistant × Rohlik.cz – Voice-driven Cart ↔ Shopping-list Sync  

This automation lets anyone in the household say **“Přidej mléko do nákupního seznamu”** (or similar) and have:

1. **Assist** add the item to the HA *Shopping list*.  
2. An **automation** immediately search the same product on Rohlik.cz and drop it in your online cart.  
3. A **script** mirror the **entire** Rohlik cart back into the Shopping list

![rohlik assist](https://github.com/user-attachments/assets/6b445598-7f4c-450c-bd20-96268f2b9a4f)

---

## Prerequisites

| Component | Purpose |
|-----------|---------|
| **[RohlikCZ integration](https://github.com/dvejsada/HA_RohlikCZ)** | API access to your Rohlik account |
| **Assist / Conversation agent** | Voice input (uses GPT-4o-mini in example) |
| **A `todo.rohlik_shopping_list` entity** | Shopping list |

---

## 1 · Conversational prompt

Add this to the “**Instructions**” field of your Assist - Conversation Agent - ⚙️ if you want to check for duplicities:

```
Při přidávání položky do nákupního seznamu zkontroluj, zda už na seznamu není. 
Pokud tam není, přidej ji bez dalšího potvrzení. 
Pokud tam už je, uveď její název a zeptej se uživatele, zda ji chce opravdu přidat znovu.
```

Effect: the LLM silently adds new items, but politely asks before creating duplicates.

### ⚠️ Known Limitation

If your voice command matches the built-in intent [`HassShoppingListAddItem`](https://github.com/home-assistant/intents/blob/main/sentences/cs/shopping_list_HassShoppingListAddItem.yaml), the request will be executed **locally by Home Assistant**, skipping the Conversation agent (LLM).  
As a result, the duplicate check in the agent prompt will **not be applied**.

**Workaround:**  
Rephrase your request to avoid triggering the default intent

---

## 2 · Script: mirror Rohlik cart → Shopping list

```
alias: "Rohlik cart to shopping list"
mode: single
sequence:
  # 1️⃣ Pull full cart
  - service: rohlikcz.get_cart_content
    data:
      config_entry_id: [your Rohlik device]
    response_variable: cart

  # 2️⃣ Build list ["Milk [2x]", "Bananas [6x]", …]
  - variables:
      product_names_with_quantity: >-
        {% set ns = namespace(lst=[]) %}
        {% for p in cart['products'] %}
          {% set ns.lst = ns.lst + [p.name ~ ' [' ~ (p.quantity | int) ~ 'x]'] %}
        {% endfor %}
        {{ ns.lst }}

  # 3️⃣ Wipe current list (mark → clear)
  - service: shopping_list.complete_all
  - service: shopping_list.clear_completed_items

  # 4️⃣ Re-create each cart line
  - repeat:
      for_each: "{{ product_names_with_quantity }}"
      sequence:
        - service: todo.add_item
          target:
            entity_id: todo.rohlik_shopping_list
          data:
            item: "{{ repeat.item }}"
```

### ⚠️ Known Limitation: Outdated Shopping List

The script that syncs the Rohlik cart to the shopping list (`script.rohlik_cart_to_shopping_list`) is currently triggered **only when an item is picked by automation below**.

This means the shopping list may become **outdated** if:
- Items are manually added to the Rohlik cart (e.g. via app or website)
- No new item has been added by voice recently

As a result, the **Conversation agent may not be aware** of what's already in the cart, and could allow duplicates unintentionally.

🧩 **Open Question:**  
What is the best way to keep the shopping list up to date **without using time-based automations** (which I’m trying to avoid)?  

---

## 3 · Automation: new spoken item → Rohlik cart

```
alias: "Rohlik Add Item From Shopping List to Cart"
mode: single

## 🔔 Trigger whenever the list length increases
trigger:
  - platform: state
    entity_id: todo.rohlik_shopping_list

## 📝 Ensure we’re reacting to an *addition*, not a removal
condition:
  - "{{ (trigger.to_state.state | int(0)) > (trigger.from_state.state | int(0)) }}"

## ▶️ Actions
action:
  # 1️⃣ Fetch full list → pick **last** item (the newly added one)
  - service: todo.get_items
    target: {entity_id: todo.rohlik_shopping_list}
    response_variable: shopping_list

  - variables:
      last_item: "{{ shopping_list['todo.rohlik_shopping_list']['items'][-1]['summary'] }}"

  # 2️⃣ Ignore items written by the sync-script (they contain “[2x]” etc.)
  - condition: "{{ '[' not in last_item }}"

  # 3️⃣ Add to Rohlik last_item
  - service: rohlikcz.search_and_add_to_cart
    data:
      config_entry_id: [your Rohlik device]
      product_name: "{{ last_item }}"
      quantity: 1

  # 4️⃣ Refresh local list so quantities stay in sync
  - service: script.rohlik_cart_to_shopping_list
```

### ⚠️ Known Limitation: Only One New Item Handled

If **multiple new items** (without `[x]` suffix) are added to the shopping list at once the automation currently processes **only the most recent one** (`[-1]` in the list).

This means:
- Only the **last added item** will be sent to the Rohlik cart
- Other new items will be removed during cart->shopping list sync while processing the first item

📝 **Note:**  
This issue should not occur when using Assist via voice, as it adds **only one item per request**.
