### ISSUE TITLE
Vynuceni aktualizace dat

### ISSUE THREAD

**Issue by mdolejsi1** [dvejsada/HA-RohlikCZ#50]
Dobrý den, prosím přes jakou entitu mam vynutit aktualizaci dat? Děkuji

**Comment by dvejsada** [comment]
> Dobrý den, prosím přes jakou entitu mam vynutit aktualizaci dat? Děkuji 

Dobrý den, nikoliv pomocí entity, ale pomocí akce (service call) rohlik.update_data. Tu lze zavolat bud automatizací (což je primární účel) nebo manuálně v Developer Tools -> Actions.

Mám přidat button entity, aby bylo možné to dělat jednoduše i z UI?

**Comment by mdolejsi1** [comment]
Volal jsem takto, ale sluzba nenalezena
type: custom:button-card
name: Aktualizovat data z Rohlíku
icon: mdi:sync
tap_action:
  action: call-service
  service: rohlik.force_update

**Comment by mdolejsi1** [comment]
Ani takto mi to nejde :)

card:
      type: custom:button-card
      icon: mdi:sync
      tap_action:
        action: call-service
        # --- OPRAVENO: Správný název služby ---
        service: rohlik.update_data

**Comment by dvejsada** [comment]
> Ani takto mi to nejde :)
> 
> card:
>       type: custom:button-card
>       icon: mdi:sync
>       tap_action:
>         action: call-service
>         # --- OPRAVENO: Správný název služby ---
>         service: rohlik.update_data

Nevím jak pro custom button card, ale pro standardní button card takto:

```yaml
show_name: true
show_icon: true
type: button
tap_action:
  action: perform-action
  perform_action: rohlikcz.update_data
  target: {}
  data:
    config_entry_id: 01JW772TJ650WVX28NERPEQ7J1
entity: update.rohlik_cz_custom_integration_update
name: Updatovat data
icon: mdi:update

```
